Cache:
  Folder:
  RetentionDays: 2
Dicom:
  ScuAeTitle: ORDERORM
  ScpHost: worklist.fluxinc.ca
  ScpPort: 1070
  ScpAeTitle: FLUX_WORKLIST
HL7:
  SenderName: ORDERORM
  ReceiverName: RECEIVER_APPLICATION
  ReceiverFacility: RECEIVER_FACILITY
  ReceiverHost: localhost
  ReceiverPort: 7777
Query:
  ScheduledStationAeTitle: # set this value to limit results to a specific station
  ScheduledProcedureStepStartDate:
    Mode: today            # today, range, specific
    DaysBefore: 1          # only used if mode is range
    DaysAfter: 1           # only used if mode is range
    Date: 2023-03-01       # only used if mode is specific
  Modality:                # set this value to limit results to a specific modality
QueryInterval: 60
Retry:
  RetryIntervalMinutes: 1
