Cache:
  Folder:
  RetentionDays: 1
Dicom:
  ScuAeTitle: ORDERORM
  ScpHost: worklist.fluxinc.ca
  ScpPort: 1070
  ScpAeTitle: FLUX_WORKLIST
HL7:
  ReceiverHost: localhost
  ReceiverPort: 7777
Query:
  PatientName:
  ScheduledStationAeTitle:
  ScheduledProcedureStepStartDate:
    Mode: range # today, range, specific
    DaysBefore: 1
    DaysAfter: 1
    Date: 2023-03-01
  Modality: MR
QueryInterval: 60
Retry:
  RetryIntervalMinutes: 1
